//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Transport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routes()
        {
            this.Traffic_schedule = new HashSet<Traffic_schedule>();
        }
    
        public int ID { get; set; }
        public string Name_of_the_Route { get; set; }
        public int TransportID { get; set; }
        public int DriverID { get; set; }
        public int StopsID { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Stops Stops { get; set; }
        public virtual Transports Transports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traffic_schedule> Traffic_schedule { get; set; }
    }
}
