//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Transport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stops()
        {
            this.Routes = new HashSet<Routes>();
        }
    
        public int ID { get; set; }
        public int Stops_name_1_ID { get; set; }
        public int Stops_name_2_ID { get; set; }
        public int Stops_name_3_ID { get; set; }
        public int Stops_name_4_ID { get; set; }
        public int Stops_name_5_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Routes> Routes { get; set; }
        public virtual Stops_name Stops_name { get; set; }
        public virtual Stops_name Stops_name1 { get; set; }
        public virtual Stops_name Stops_name2 { get; set; }
        public virtual Stops_name Stops_name3 { get; set; }
        public virtual Stops_name Stops_name4 { get; set; }
    }
}
