//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Transport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic_schedule
    {
        public int ID { get; set; }
        public int RouteID { get; set; }
        public System.TimeSpan Departure_time { get; set; }
        public System.TimeSpan Arrival_time { get; set; }
        public int Number_of_Flights { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
